#!/bin/bash
#
# Copyright 2016 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e -v
cd "$(dirname "$0")/.."

# Deploy the Javascript and SWF files to be used by the demos.
gsutil cp dist/marzipano.js gs://www.marzipano.net/build/marzipano.js
gsutil cp dist/marzipano.swf gs://www.marzipano.net/build/marzipano.swf

# Deploy the release archive.
gsutil cp dist/*.zip gs://www.marzipano.net/releases/

# Deploy the JSON manifest.
gsutil cp dist/latest.json gs://www.marzipano.net/releases/latest.json

# Deploy the documentation.
gsutil -m rsync -r docs gs://www.marzipano.net/reference

# Deploy the demos.
gsutil -m rsync -r demos gs://www.marzipano.net/demos
